services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: "weezydb"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  redis_data:
  postgres_data:

networks:
  app_network:
    driver: bridge